name: Release app for Windows, Linux and macOS

on:
  push:
    tags:
    - '*'

jobs:
  update_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install winget
        uses: Cyberboss/install-winget@v1
  
      - name: Install wingetcreate
        run: winget install wingetcreate --disable-interactivity --accept-source-agreements      
          
      - name: Install 7zip
        run: |
          winget install 7zip --force

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true

      - name: Build Windows application
        run: |
          pyinstaller --noconfirm --distpath dist cnet_win.spec

      - name: Generate .zip file
        run: |
          7z a -r release_win.zip ./dist/*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_win
          path: ./release_win.zip

  mac_update_and_release:
    runs-on: macos-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # specify your Python version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip 
          pip3 install -r requirements.txt

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true

      - name: Build macOS application
        run: |
          pip3 install py2app
          rm -rf build dist
          sed -i '.bak' -e 's/version="1.0.0"/version="${{ github.ref_name }}"/g' setup.py
          python3 setup.py py2app

      - name: Generate .dmg package
        uses: Lethja/create-dmg-action@v0.0.2
        with:
          name: 'CNetMinecraftLauncher'
          srcdir: 'dist/'

      - name: Upload dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_macos
          path: ./CNetMinecraftLauncher.dmg

  linux_update_and_release:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # specify your Python version

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3.10 -y
          sudo apt install python3-tk -y

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true

      - name: Build Linux Application
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pyinstaller --noconfirm --distpath dist cnet_linux.spec

      - name: Change rights
        run: |
          chmod -R u+r+w+x,g+r+w+x,o+r-w+x dist/cnet_launcher/_internal
          chmod a+w dist/cnet_launcher/_internal/scripts/sh_log_cnet.txt

      - name: Generate .zip file
        run: |
          zip -r release_linux.zip ./dist/*
          
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_linux
          path: ./release_linux.zip


  release:
    runs-on: ubuntu-latest
    
    needs: [linux_update_and_release, update_and_release, mac_update_and_release]
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release_win
          path: .
          
      - uses: actions/download-artifact@v4
        with:
          name: release_linux
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: release_macos
          path: .
                
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release_win.zip,release_linux.zip,CNetMinecraftLauncher.dmg"
