name: Update and Release Launcher

on:
  push:
    tags:
    - '*'

jobs:
  update_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install winget
        uses: Cyberboss/install-winget@v1
  
      - name: Install wingetcreate
        run: winget install wingetcreate --disable-interactivity --accept-source-agreements      
          
      - name: Install 7zip
        run: |
          winget install 7zip --force

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true


      - name: Build .exe
        run: |
          pip install pyinstaller
          pyinstaller --windowed --i "_internal/icon.ico" --add-data "_internal/icon.ico;." --add-data "_internal/scripts;scripts" --add-data "_internal/java/win;java/win" --add-data "_internal/.minecraft;.minecraft" --name "cnet_launcher" --distpath dist/ main.py

      - name: Generate .zip file
        run: |
          7z a -r release_win.zip ./dist/*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_win
          path: ./release_win.zip
        

  mac_update_and_release:
    runs-on: macos-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # specify your Python version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip 
          pip3 install -r requirements.txt

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true

      - name: Build .exe
        run: |
          pip3 install py2app
          rm -rf build dist
          sed -i '.bak' -e 's/version="1.0.0"/version="${{ github.ref_name }}"/g' setup.py
          python3 setup.py py2app

      - name: Change permissions and rights
        run: |
          chflags -R nouchg dist/CNetMinecraftLauncher.app
          chmod -R u+r+w+x,g+r+w+x,o+r-w+x dist/CNetMinecraftLauncher.app
          chmod a+w dist/CNetMinecraftLauncher.app/Contents/Resources/_internal/scripts/sh_log_cnet.txt
          chmod -R -N dist/CNetMinecraftLauncher.app

      - name: Generate .zip file
        run: |
          zip -r release_macos.zip ./dist/*

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_macos
          path: ./release_macos.zip

  linux_update_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Launcher Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # specify your Python version

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt update
          sudo apt upgrade -y
          sudo apt install python3.12 -y
          sudo apt install python3-tk -y

#      - name: Download artifact
#        id: download-artifact
#        uses: dawidd6/action-download-artifact@v2
#        with:
#          name: ELN_mod
#          repo: patrudaz/ElectricalAge
#          workflow: main.yml
#          path: ./_internal/.minecraft/mods
#          search_artifacts: true

      - name: Download map
        id: download-map
        uses: dawidd6/action-download-artifact@v2
        with:
          name: cnet_map
          repo: patrudaz/cnet_files
          workflow: main.yml
          path: ./_internal/.minecraft/saves
          search_artifacts: true

      - name: Build .exe
        run: |
          sudo pip3 install pyinstaller
          pyinstaller --windowed --i "icon.xbm" --add-data "_internal/icon.xbm:." --add-data "_internal/scripts:scripts" --add-data "_internal/java/linux:java/linux" --add-data "_internal/.minecraft:.minecraft" --name "cnet_launcher" --distpath dist/ main.py      

      - name: Change rights
        run: |
          chmod a+x -R dist/cnet_launcher/_internal/scripts
          chmod a+w dist/cnet_launcher/_internal/scripts/sh_log_cnet.txt
          chmod a+x -R dist/cnet_launcher/_internal/java/linux

      - name: Generate .zip file
        run: |
          zip -r release_linux.zip ./dist/*
          
      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_linux
          path: ./release_linux.zip


  release:
    runs-on: ubuntu-latest
    
    needs: [linux_update_and_release, update_and_release, mac_update_and_release]
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release_win
          path: .
          
      - uses: actions/download-artifact@v4
        with:
          name: release_linux
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: release_macos
          path: .
                
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release_win.zip,release_linux.zip,release_macos.zip"
