name: Build and Release

on:
  push:
    branches:
      - standby  # not using this workflow for the moment

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build .exe
      run: |
        pip install pyinstaller
        pyinstaller --windowed --add-data "scripts;scripts" --add-data ".minecraft;.minecraft" --name "cnet_launcher" --distpath dist/cnet_launcher main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: launcher
        path: dist  # adjust based on your project structure
